- name: "Write config file"
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0600'
  register: template_apply_result

- name: Restart service after config change
  ansible.builtin.service:
    name: rke2-server.service
    state: restarted
  when: template_apply_result.changed
