# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/rke2-server


- name: Install RKE2 Server
  ansible.builtin.include_tasks: install.yml

- name: Apply RKE2 configuration
  ansible.builtin.include_tasks: configure.yml

- name: Configure RKE2 service
  ansible.builtin.include_tasks: service.yml
