#cloud-config

hostname: rocky-cloud
manage_etc_hosts: true

users:
  - name: aadil279
    gecos: Aadil Sidik
    shell: /bin/bash
    groups: wheel
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID1Q/s45joJD5NKBe8cSvAOD+CAvRCvCoCMi+6E7Bfkd


  - name: ansible
    gecos: Ansible User
    shell: /bin/bash
    groups: wheel
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEtHC4wlwUzN+tkfLFcv/dmV+DYU++bW//IPMmLIuLc3

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable --now qemu-guest-agent
